version: "3.8"

services:
  front:
    build:
      context: ./taskFlow
      dockerfile: Dockerfile
    image: taskflow:1.0
    container_name: angular_app
    restart: unless-stopped
    ports:
      - "80:80"   
    depends_on:
      - backend

  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    image: backend:1.0
    container_name: spring_app
    restart: unless-stopped
    ports:
      - "8090:8090"   #
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todo?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: appuser     
      SPRING_DATASOURCE_PASSWORD: apppass
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    #  REMOVE in production (keep only for dev)
    # ports:
    #   - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data: