apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
  labels:
    app: taskflow-frontend
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-frontend
  template:
    containers:
      - name: frontend
        image: hazem231/taskflow:latest
      ports: 
        - containerPort: 80
